warp:
  sources:
    - path: /dogu
      type: dogus
      tag: warp
    - path: /externals
      type: externals
    - path: /support
      type: support
  target: /var/www/html/warp/menu.json
  order:
    External Links: 2
    Support: 3

  support:
    - identifdier: docsCloudoguComUrl
      external: true
    - identifdier: aboutCloudoguToken
      external: false
    - identifdier: myCloudogu
      external: true

service:
  source:
    path: /services
  target: /etc/nginx/conf.d/app.conf
  template: /etc/ces-confd/templates/nginx.app.tpl
  maintenance-mode: /config/_global/maintenance
  tag: webapp
  ignore-health: false

maintenance:
  source:
    path: /config/_global/maintenance
  default:
    title: Maintenance
    text: The EcoSystem is currently in maintenance mode
  target: /var/www/html/maintenance.html
  template: /etc/ces-confd/templates/maintenance.tpl
