warp:
  sources:
    - path: /dogu
      type: dogus
      tag: warp
    - path: /externals
      type: externals
  target: /var/www/html/warp/menu.json
  order:
    External Links: 2
service:
  source:
    path: /services
  target: /etc/nginx/conf.d/app.conf
  template: /etc/ces-confd/templates/nginx.app.tpl
  tag: webapp
maintenance:
  source:
    path: /config/_global/maintenance
  target: /var/www/html/maintenance.html
  template: /etc/ces-confd/templates/maintenance.tpl
