// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import client "github.com/coreos/etcd/client"
import mock "github.com/stretchr/testify/mock"

// Registry is an autogenerated mock type for the Registry type
type Registry struct {
	mock.Mock
}

// Get provides a mock function with given fields: key
func (_m *Registry) Get(key string) (*client.Response, error) {
	ret := _m.Called(key)

	var r0 *client.Response
	if rf, ok := ret.Get(0).(func(string) *client.Response); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Watch provides a mock function with given fields: key, recursive, eventChannel
func (_m *Registry) Watch(key string, recursive bool, eventChannel chan *client.Response) {
	_m.Called(key, recursive, eventChannel)
}
